DirectoryBook/Models/Name.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DirectoryBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Name
    {
      
    
        public int Id { get; set; }



         [Display(Name = "Name")]
         [Required(ErrorMessage = "The field must be set")]
         [StringLength(20, MinimumLength = 3, ErrorMessage = "The string length must be between 3 and 20 characters")]
         public string TName { get; set; }


          [Display(Name = "Surname")]
          [Required(ErrorMessage = "The field must be set")]
          [StringLength(20, MinimumLength = 3, ErrorMessage = "The string length must be between 3 and 20 characters")]
          public string Surname { get; set; }
    
        public virtual ICollection<Phone> Phones { get; set; }
    }
}

DirectoryBook/Models/PersonsDBModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectoryBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonsDBEntities : DbContext
    {
        public PersonsDBEntities()
            : base("name=PersonsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Name> Names { get; set; }
        public DbSet<Phone> Phones { get; set; }
    }
}

DirectoryBook/Models/PersonsDBModel.Designer.cs
// Default code generation is disabled for model 'D:\програм\DirectoryBook\DirectoryBook\Models\PersonsDBModel.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

DirectoryBook/Models/PersonsDBModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

DirectoryBook/Models/Phone.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DirectoryBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Id { get; set; }

        [Display(Name = "Telephone")]
        [StringLength(20, MinimumLength = 12, ErrorMessage = "The string length must be between 12 and 20 characters")]
        public string Tel { get; set; }

        [Display(Name = "Additional Information")]
        public string Additional_Information { get; set; }

        public Nullable<int> PersonId { get; set; }
    
        public virtual Name Name { get; set; }
    }
}

DirectoryBook/Controllers/DirectoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirectoryBook.Models;


namespace DirectoryBook.Controllers
{
    public class DirectoryController : Controller
    {
        //
        // GET: /Directory/

        private PersonsDBEntities db= new PersonsDBEntities();

        public ActionResult ShowData()
        {
            
            var persons = db.Phones.Include(n => n.Name);

                return View(persons.ToList());

           
        }
        [HttpGet]
        public ActionResult AddData()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddData(Phone phone,Name name)
        {
           
            try
            {

                if (ModelState.IsValid)
                {

                    db.Names.Add(name);
                    db.Phones.Add(phone);
                    db.SaveChanges();
                    return RedirectToAction("ShowData");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex);
            }

            return View();


        }
        [HttpGet]
        public ActionResult EditData(int? id)
        {

            Phone phone = db.Phones.Single(s => s.Id == id);

            return View(phone);
        }

        [HttpPost]
        public ActionResult EditData(Phone phone)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var dbPhone = db.Phones.Where(x => x.Id == phone.Id).FirstOrDefault();
                    if (dbPhone == null) return RedirectToAction("ShowData");
                    dbPhone.Name.TName = phone.Name.TName;
                    dbPhone.Name.Surname = phone.Name.Surname;
                    dbPhone.Name = phone.Name;
                    dbPhone.Tel = phone.Tel;
                    dbPhone.Additional_Information = phone.Additional_Information;
                    db.SaveChanges();
                    return RedirectToAction("ShowData");
                }


            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex);
            }

            return View();
        }

        public ActionResult Delete(int? id)
        {

            Phone phone = db.Phones.Single(s => s.Id == id);

            return View(phone);

        }

        [HttpPost]
        public ActionResult Delete(Phone phone)
        {
            try
            {
                var dbPhone = db.Phones.Where(x => x.Id == phone.Id).FirstOrDefault();
                if (dbPhone == null) return RedirectToAction("ShowData");
                db.Phones.Remove(dbPhone);
                db.SaveChanges();

                return RedirectToAction("ShowData");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex);
                return View();
            }

        }

        }

    }

DirectoryBook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DirectoryBook.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

DirectoryBook/Views/Directory/AddData.cshtml
@{
    ViewBag.Title = "Add Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DirectoryBook.Models.Phone
@section adding{
    
    @using (Html.BeginForm("AddData", "Directory", FormMethod.Post, new { id = "PersonForm" }))
{ 
        
        <p>
            @Html.LabelFor(m => m.Name.TName, "First Name")
            <br />
            @Html.TextBoxFor(m => m.Name.TName)
            @Html.ValidationMessageFor(m => m.Name.TName)
          
        </p>
        <p>
            @Html.LabelFor(m => m.Name.Surname, "Last Name")
            <br />
            @Html.TextBoxFor(m => m.Name.Surname)
            @Html.ValidationMessageFor(m => m.Name.Surname)
 
        </p>
    <p>
        @Html.LabelFor(m => m.Tel, "Telephone")
        <br />
        @Html.TextBoxFor(m => m.Tel) 
        @Html.ValidationMessageFor(m => m.Tel)
    </p>
        
        <p>
            @Html.LabelFor(m => m.Additional_Information, "Additional Information")
            <br />
            @Html.TextBoxFor(m => m.Additional_Information)
            @Html.ValidationMessageFor(m => m.Additional_Information)
        </p>
        <p><input type="submit" value="Send" /> @Html.ActionLink("Return to the Directory","ShowData","Directory")</p>
  
}
}
    

DirectoryBook/Views/Directory/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model  DirectoryBook.Models.Phone
@section delete
{
    <h3>Are you sure that you want to delete this person?</h3>


    <div class="display-label">Name:</div>
    <div class="display-field">@Model.Name.TName</div>

    <div class="display-label">Surname:</div>
    <div class="display-field">@Model.Name.Surname</div>
    
    <div class="display-label">Telephone:</div>
    <div class="display-field">@Model.Tel</div>



    @using (Html.BeginForm())
    {
        <p>
            <input type="submit" value="Delete" /> |
            @Html.ActionLink("No, Back to Dictionary", "ShowData")
        </p>
    }
}

DirectoryBook/Views/Directory/EditData.cshtml
@{
    ViewBag.Title = "Edit Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DirectoryBook.Models.Phone
@section edition{


@using (Html.BeginForm("EditData", "Directory", FormMethod.Post, new { id = "PersonForm" }))
{
    
        @Html.HiddenFor(m => m.Id)
       <p>
            @Html.LabelFor(m => m.Name.TName, "First Name")
            <br />
            @Html.EditorFor(m => m.Name.TName)

            @Html.ValidationMessageFor(m => m.Name.TName)
          
        </p>
        <p>
            @Html.LabelFor(m => m.Name.Surname, "Last Name")
            <br />
            @Html.EditorFor(m => m.Name.Surname)

            @Html.ValidationMessageFor(m => m.Name.Surname)
 
        </p>
        <p>
            @Html.LabelFor(m => m.Tel, "Telephone")
            <br />
            @Html.EditorFor(m => m.Tel)
            @Html.ValidationMessageFor(m => m.Tel)
        </p>
        <p>
            @Html.LabelFor(m => m.Additional_Information, "Additional Information")
            <br />
            @Html.EditorFor(m => m.Additional_Information)
            @Html.ValidationMessageFor(m => m.Additional_Information)
        </p>
        <p><input type="submit" value="Send" />@Html.ActionLink("Return to the Directory","ShowData","Directory")</p>

}
}

DirectoryBook/Views/Directory/ShowData.cshtml
@model IEnumerable<DirectoryBook.Models.Phone>

@{
    ViewBag.Title = "Directory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section data{

    <p>
        @Html.ActionLink("Add New Contact", "AddData")
    </p>
    <table>
        <tr>
            <th>
                Name
            </th>
            <th>
                Surname
            </th>
            <th>
                Telephone
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name.TName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tel)
                </td>

                <td>
                    @Html.ActionLink("Edit", "EditData", new {id = item.Id}) |
                    @Html.ActionLink("Delete", "Delete", new {id = item.Id})
                </td>
            </tr>
        }

    </table>
}

DirectoryBook/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section main
{
    
    
     <img src="~/Content/Images/Untitled-4.png" />
}

DirectoryBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/stylesheet.css")
</head>
    <body>
        <div id="top_bar_black"> <div class="nav_button">@Html.ActionLink("Main","Index","Home",null,new { id = "menu" })</div>
	  <div class="nav_button">@Html.ActionLink("Directory","ShowData","Directory",null,new { id = "menu" }) </div>
 </div>
        <div id="content_container">
            <div id="header"> <div class="header_content_mainline"> Telephone directory of Kharkov </div>  
                @RenderSection("data",required:false)  
                @RenderSection("main",required:false)   
                @RenderSection("edition",required:false)   
                @RenderSection("adding",required:false)  
                @RenderSection("delete",required:false) 
            </div>  
</div> 
</body>
</html>